#!/bin/bash

priv_ip_addr=$(ip -4 -o addr | grep "scope global" | awk '{ print $4 }' | awk '{ print $1 }' FS=/ | head -1)
this_script=$(realpath $0)
aws_dir=$(dirname ${this_script})
data_dir=$(realpath ${aws_dir}/../../data)

sqlite3 ${data_dir}/aws.sqlite "select host from hosts where PrivateIpAddress=\"${priv_ip_addr}\""
