---
# tasks file for jupyter_nbgrader

- name: install pip3 nbgrader
  pip:
    name:
      - nbgrader
    state: present
    # - nbconvert
    # - nbconvert==5.6

- name: make /home/share/nbgrader
  file:
    dest: /home/share/nbgrader
    state: directory
    owner: share
    group: share
    mode: 0777

- name: make /home/share/nbgrader/exchange
  file:
    dest: /home/share/nbgrader/exchange
    state: directory
    owner: share
    group: share
    mode: 0777

- name: make link to exchange directory (/usr/local/share/nbgrader)
  file:
    src: /home/share/nbgrader
    dest: /usr/local/share/nbgrader
    state: link
    force: yes

