---
# tasks file for jupyter

- name: install pip3 npm libcurl4-openssl-dev libssl-dev
  apt:
    name:
      - python3-pip
      - npm
      - libcurl4-openssl-dev
      - libssl-dev
    state: present
  
- name: install pip3 module tornado jupyter matplotlib notebook jupyterlab jupyterhub jupyterhub-idle-culler pixiedust
  pip:
    name:
      - jupyterhub==4.0.2
      - jupyterhub-idle-culler
      - pycurl
      # - tornado
      # - jupyter
      # - matplotlib
      # - notebook
      # - jupyterlab
      # - pixiedust
    state: present


    
- name: install npm module configurable-http-proxy
  npm:
    name: configurable-http-proxy
    state: present
    global: yes

