---
# tasks file for nfs_server

- name: move HOME of mdxuser to /home.local
  include_role:
      name: mv_home_mdxuser

- name: install nfs server
  apt:
    name: nfs-kernel-server
    state: present

- name: export /home via NFS
  lineinfile:
    path: /etc/exports
    state: present
    regexp: "^/home "
    line: "/home {% for addr, v in hostvars.items() %} {{ v.rdmaipv4 }}(rw,no_root_squash,no_subtree_check){% endfor %}"

- name: re-export all directories
  command: exportfs -ra

