---
# tasks file for jupyter_vpython

# nbgrader 0.8.2 has requirement jupyter-client<8, but you'll have jupyter-client 8.1.0 which is incompatible.
# => jupyter-client==7.4.9

- name: install pip3 module jupyter-client jupyter-server-proxy jupyterlab-vpython vpnotebook vpython
  pip:
    name:
      - jupyter-client==7.4.9
      - jupyter-server-proxy
      - vpython
#      - vpython-jupyter
      - vpnotebook
#      - jupyterlab_vpython
      - jupyterlab-vpython
    state: present

# - name: install patched vpython-jupyter
#   shell:
#     cmd: rm -rf vpython-jupyter && git clone https://github.com/taura/vpython-jupyter && cd vpython-jupyter && python3 setup.py install

- name: print vpython_dir
  shell:
    cmd: python3 -c 'import vpython,os; print(os.path.dirname(vpython.__file__), flush=True); os._exit(0)'
  register: print_vpython_dir

# - name: set vpython_dir
#   debug:
#     msg: "{{ print_vpython_dir }}"
    
- name: set vpython_dir
  set_fact:
    vpython_dir: "{{ print_vpython_dir.stdout }}"
    
- name: copy static files
  shell:
    cmd: rsync -avz {{ vpython_dir }}/vpython_data /usr/local/share/jupyter/lab/static/
  
# when vpython is installed in the system directory for everybody,
# then the following error happens when a user first uses a graphics
# function (e.g., sphere())
#
# PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/static/vpython_data/rough_texture.jpg'
#
# this happens because vpython tries to install some static images
# (such as textures) into the notebook directory when it finds
# they have not been installed (or the source is newer than dest).
# but the destination is writable only by root.
#
# specifically, the source seems something like
# /usr/local/lib/python3.8/dist-packages/vpython-7.5.0+9.g8888e89-py3.8.egg/vpython/vpython_data
# and the destination is
# /usr/local/share/jupyter/lab/static/vpython_data
#
# the above rsync commands make sure that the former becomes newer than the latter
#
# a smarter way is to invoke the installation as a root, but
# I don't know how to do it in the command line (without a browser)
#
# I initially thought the following works the problem around, but it doesn't
#
# mkdir -p /usr/local/share/jupyter/lab/static/vpython_data -m 777

