---

- name: basics
  hosts: default
  vars_files: [ vars/basics.yml ]
  roles:
    - basics

- name: nfs server
  hosts: nfs_server
  roles:
    - nfs_server

- name: nfs client
  hosts: default
  roles:
    - nfs_client

- name: ldap server
  hosts: ldap_server
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_server

- name: ldap client
  hosts: default
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_client

- name: ldap users
  hosts: ldap_server
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_users

- name: invalidate sss cache
  hosts: default
  roles:
    - sss_invalidate

- name: make ldap_sudo sudoers
  hosts: default
  roles:
    - ldap_sudo
    
- name: apache
  hosts: web_server
  vars_files: [ vars/cert.yml ]
  roles:
    - apache
    - cert

- name: cgroup2
  hosts: default
  roles:
    - cgroup2

- name: remote desktop
  hosts: desktop
  roles:
    - xrdp

# - name: cuda (install on all hosts to cross-compile)
#   hosts: default
#   roles:
#     - cuda

# - name: nvidia_hpc_sdk (install on all hosts to cross-compile)
#   hosts: default
#   roles:
#     - nvidia_hpc_sdk

# - name: pytorch_cpu
#   hosts: cpu
#   roles:
#     - pytorch_cpu

# - name: pytorch_gpu
#   hosts: gpu
#   roles:
#     - pytorch_gpu

- name: jupyter
  hosts: default
  vars_files: [ vars/jupyter.yml ]
  roles:
    - jupyter
    - jupyter_bash
    - jupyter_sos
    - jupyter_nbgrader
    # - jupyter_ocaml
    # - jupyter_vpython
    # - jupyter_c
    # - jupyter_julia
    # - jupyter_rust
    # - jupyter_go
    # - jupyter_fixup             # jinja2 version

- name: Lustre
  hosts: default
  roles:
    - lustre

# - name: slurm
#   hosts: slurm_control
#   vars_files: [ "{{ slurm_vars_file }}" ]
#   roles:
#     - slurm_control

# - name: slurm
#   hosts: slurm_node
#   vars_files: [ "{{ slurm_vars_file }}" ]
#   roles:
#     - slurm_node

