---

- name: basics
  hosts: default
  vars_files: [ vars/basics.yml ]
  roles:
    - basics

# conflict with lustre
- name: cgroup2
  hosts: default
  roles:
    - cgroup2

- name: reboot
  hosts: default
  roles:
    - reboot

- name: nfs server
  hosts: nfs_server
  roles:
    - nfs_server

- name: nfs client
  hosts: default
  roles:
    - nfs_client

- name: ldap server
  hosts: ldap_server
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_server

- name: ldap client
  hosts: default
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_client

- name: ldap users
  hosts: ldap_server
  vars_files: [ "{{ ldap_vars_file }}" ]
  roles:
    - ldap_users

- name: invalidate sss cache
  hosts: default
  roles:
    - sss_invalidate

- name: make ldap_sudo sudoers
  hosts: default
  roles:
    - ldap_sudo

# conflict with cgroups    
- name: lustre
  hosts: none
  roles:
    - lustre

- name: apache
  hosts: web_server
  vars_files: [ vars/cert.yml ]
  roles:
    - apache
    - cert

- name: jupyter
  hosts: default
  vars_files: [ vars/jupyter.yml ]
  roles:
    - jupyter
    - jupyter_bash
    - jupyter_sos
    - jupyter_nbgrader

- name: remote desktop
  hosts: none
  roles:
    - xrdp

- name: cuda (install on all hosts to cross-compile)
#  hosts: default
  hosts: none
  roles:
    - cuda

- name: nvidia_hpc_sdk (install on all hosts to cross-compile)
#  hosts: default
  hosts: none
  roles:
    - nvidia_hpc_sdk

- name: pytorch_cpu
#  hosts: cpu
  hosts: none
  roles:
    - pytorch_cpu

- name: pytorch_gpu
#  hosts: gpu
  hosts: none
  roles:
    - pytorch_gpu

- name: slurm
#  hosts: slurm_control
  hosts: none
  vars_files: [ "{{ slurm_vars_file }}" ]
  roles:
    - slurm_control

- name: slurm
#  hosts: slurm_node
  hosts: none
  vars_files: [ "{{ slurm_vars_file }}" ]
  roles:
    - slurm_node

