#wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
#sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
# wget https://developer.download.nvidia.com/compute/cuda/11.7.1/local_installers/cuda-repo-ubuntu2004-11-7-local_11.7.1-515.65.01-1_amd64.deb
# sudo dpkg -i cuda-repo-ubuntu2004-11-7-local_11.7.1-515.65.01-1_amd64.deb
# sudo cp /var/cuda-repo-ubuntu2004-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/
# sudo apt-get update
# sudo apt-get -y install cuda


- name: update pci.ids
  shell: update-pciids

- name: download a apt-preference file for nvidia drivers
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
    dest: /etc/apt/preferences.d/cuda-repository-pin-600

- name: add nvidia apt-key
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    state: present

- name: add cudnn repository
  ansible.builtin.apt_repository:
    repo: deb http://archive.canonical.com/ubuntu hardy partner
    state: present
    

- name: install nvidia drivers
  apt:
    update_cache: yes
    state: present
    name:
      - cuda-11-7

# You need to join NVIDIA developper network
# https://developer.nvidia.com/
# go and download following file(s) 
# from https://developer.nvidia.com/rdp/cudnn-download
# and save it under ../../../files/

- name: copy cudnn packages to the virtual machine
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - ./files/libcudnn8_8.5.0.96-1+cuda11.7_amd64.deb
#    - ./files/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb
#    - ./files/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb

- name: apt update
  apt:
    update_cache: yes

- name: install cudnn libraries
  apt:
    deb: "{{ item }}"
  with_items:
    - /tmp/libcudnn8_8.5.0.96-1+cuda11.7_amd64.deb
    # - /tmp/libcudnn8-dev_8.2.2.26-1+cuda11.4_amd64.deb
    # - /tmp/libcudnn8_8.2.2.26-1+cuda11.4_amd64.deb

- name: install cudnn dependent libraries
  apt:
    update_cache: yes
    name:
      - cuda-cudart-11-7
      - cuda-cudart-dev-11-7
      - libcublas-11-7
      - libcublas-dev-11-7
      - libcusolver-11-7
      - libcusolver-dev-11-7
      - libcusparse-11-7
      - libcusparse-dev-11-7

# - name: download nvidia GPU drivers
#   get_url:
#     url: https://developer.download.nvidia.com/compute/cuda/11.4.1/local_installers/cuda-repo-ubuntu2004-11-4-local_11.4.1-470.57.02-1_amd64.deb
#     dest: /tmp/cuda-repo-ubuntu2004-11-4-local_11.4.1-470.57.02-1_amd64.deb

# - name: install nvidia GPU drivers
#   apt:
#     deb: /tmp/cuda-repo-ubuntu2004-11-4-local_11.4.1-470.57.02-1_amd64.deb

# - name: install nvidia drivers
#   apt:
#     update_cache: yes
#     state: present
#     install_recommends: no
#     name:
#       - nvidia-headless-470
#       - nvidia-utils-470
#       - nvidia-cuda-toolkit

